### ISSUE TITLE
🐛 Import package issue on `v0.2.2`

### ISSUE THREAD

**Issue by MartinGbz** [duneanalytics/ts-dune-client#68]
It seems since the version `0.2.2` (published a few hours ago from this post) the package is not recognized anymore in JS/TS projects.

I haven't dug into it yet, but I've just tried importing it into 2 different repo and I got the same issue:

- code: `import { DuneClient } from "@duneanalytics/client-sdk";`
⬇️
- error: `Cannot find module '@duneanalytics/client-sdk' or its corresponding type declarations.`

Before `v0.2.2` I didn't have any issue with the package.

**Comment by bh2smith** [comment]
Fixed in https://github.com/duneanalytics/ts-dune-client/releases/tag/v0.2.3 by #69

Thanks for reporting and sorry for the hassle.

**Comment by bh2smith** [comment]
Ok there is still an issue here because we import package.json to read the package version. Will need to make one more change.

**Comment by bh2smith** [comment]
Very sorry - this should do the trick

https://github.com/duneanalytics/ts-dune-client/releases/tag/v0.2.4

**Comment by bh2smith** [comment]
Tested here:

https://github.com/bh2smith/demo-ts-dune-client/pull/8

**Comment by MartinGbz** [comment]
I confirm it works now, thanks for your reactivity sir! 🙏
